# Generated by Django 4.1.7 on 2023-04-22 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedaegu',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storedaegu',
            name='rating_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='storedaegu',
            table=None,
        ),
    ]
