# Generated by Django 4.1.7 on 2023-04-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storedaegu_likes_alter_storedaegu_rating_mean_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedaegu',
            options={'ordering': ['store_id']},
        ),
    ]
