# Generated by Django 4.1.7 on 2023-04-27 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_alter_storedaegu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedaegu',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
