# Generated by Django 4.1.7 on 2023-04-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_storedaegu_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedaegu',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
