# Generated by Django 4.1.7 on 2023-05-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_review_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedaegu',
            name='rating_mean',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.review')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storedaegu')),
            ],
        ),
    ]
