# Generated by Django 4.1.7 on 2023-05-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0008_alter_storedaegu_rating_mean_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
